### ISSUE TITLE
[BUG] New record replays are not working correctly

### ISSUE THREAD

**Issue by erikjunker** [surftimer/SurfTimer#146] opened 2020-05-19 10:47 UTC
**Describe the bug**
New record replays are bugged out - it's like they record the previous 2-3 attempts instead of the actual run. On bonuses they reset 2-3 times and then replay is basically over. So you never see the actual run.
On map records they also record the 2-3 previous attempts (so you actually see the player is resetting). This causes the bot to glitch out and show the replay completely out of sync. This did not happen on the stable release.

**Expected behavior**
Bots should show the records correctly.

**Screenshots**

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
Latest dev branch

**Additional context**

**Comment by FR33K1LL** [comment] 2020-05-19 19:42
Can confirm i am getting this bug as well, shows any attempt on the replay, fail or wr, and sometimes just shows 3 fails.

**Comment by Kyli3Boi** [comment] 2020-05-19 19:58
Im having same issue

**Comment by FR33K1LL** [comment] 2020-05-20 00:07
is this similar to #76

**Comment by Kyli3Boi** [comment] 2020-05-20 00:46
@FR33K1LL no this is a different issue, I managed to sort out my issue in #76 by wiping my entire db and starting over but I now have this issue. Let's say a player has 3 runs but the first 2 runs he fails and the 3rd he gets wr, the bot will sometimes play those 2 failed runs and then the wr but also won't play the full wr run as the time is being taken up by the failed runs

**Comment by FR33K1LL** [comment] 2020-05-20 00:55
^ same

**Comment by erikjunker** [comment] 2020-05-21 13:34
Only commit I could find changing anything related to the replay bots was this one:
e1a7d2401ccec6085e47abad7bd76218bbd4979a

Could this possibly be the culprit?

**Comment by erikjunker** [comment] 2020-05-21 14:41
Well, I just tried reverting these three commits on my own branch and now the replays are working again:
effc1108f890775c88714f671302d5f7c62b4901
e1a7d2401ccec6085e47abad7bd76218bbd4979a
129a8f2054777b7b390db12f6291c56ac7498e89

Perhaps @LubricantJam can advise?

**Comment by bctse** [comment] 2020-05-21 15:27
Just wanted to note that I been having the same issues with my replay bot. I've had the issue since version 281, right now im on version 285.

**Comment by FR33K1LL** [comment] 2020-05-21 21:48
> Well, I just tried reverting these three commits on my own branch and now the replays are working again:
> [effc110](https://github.com/surftimer/Surftimer-olokos/commit/effc1108f890775c88714f671302d5f7c62b4901)
> [e1a7d24](https://github.com/surftimer/Surftimer-olokos/commit/e1a7d2401ccec6085e47abad7bd76218bbd4979a)
> [129a8f2](https://github.com/surftimer/Surftimer-olokos/commit/129a8f2054777b7b390db12f6291c56ac7498e89)
> 
> Perhaps @LubricantJam can advise?

I will try reverting these commits tonight as well and report back.

**Comment by royysz** [comment] 2020-05-23 20:26
Also having the same issue, can you update the main release so I can update my server?
Thanks

**Comment by FR33K1LL** [comment] 2020-05-24 11:52
> [effc110](https://github.com/surftimer/Surftimer-olokos/commit/effc1108f890775c88714f671302d5f7c62b4901)
> [e1a7d24](https://github.com/surftimer/Surftimer-olokos/commit/e1a7d2401ccec6085e47abad7bd76218bbd4979a)
> [129a8f2](https://github.com/surftimer/Surftimer-olokos/commit/129a8f2054777b7b390db12f6291c56ac7498e89)

Reverting these commits seemed to cause another glitch in replays where it will abruptly end and reset the replay. Im also getting alot more bots doing the clip/not hitting the tele and flying all over the place. Im gonna revert back for now.

**Comment by erikjunker** [comment] 2020-05-24 12:20
My replays do not abruptly end with those commits reverted, but the bots sometimes fly all over the place with certain triggers and boosts. It's better than all replays being broken though, so I'll keep those commits reverted on my servers until this has been looked into..

**Comment by FR33K1LL** [comment] 2020-05-24 12:31
U know what, i spoke too soon. Im getting normal behavior and havent seen any failed run replays i dont think. It was just on that one map it seemed off.

**Comment by FR33K1LL** [comment] 2020-05-25 19:46
^nope theres still failed runs

**Comment by erikjunker** [comment] 2020-05-25 19:53
Yes - I was able to replicate that now as well @FR33K1LL. But even with the failed runs, the bot still has the entirety of the actual record. I assume this is the case for you as well?

**Comment by bctse** [comment] 2020-05-31 07:50
Yeah the replay bot now shows 2-3 failed runs before the actual record run.

**Comment by olokos** [comment] 2020-06-01 20:19
#145 is related

**Comment by Bara** [comment] 2020-09-27 11:55
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by dPexxIAM** [comment] 2021-09-22 19:36
Most likely fixed with https://github.com/surftimer/Surftimer-Official/commit/4e61df3f9525ef057e141ea1e639b67c0fdc79d9

**Comment by DaLLuZZ** [comment] 2021-09-25 20:18
Was not fixed with https://github.com/surftimer/Surftimer-Official/commit/4e61df3f9525ef057e141ea1e639b67c0fdc79d9
this bug did not exist at all in 285
```
Timer Version
Latest dev branch
```

**Comment by Bara** [comment] 2021-09-25 22:02
> Latest dev branch

dev-Branch is commits ahead and behind, but in most cases not really "up2date" and ready to run. I wrote it somewhere, we should rename the dev-Branch to old_dev or so.

**Closed** 2022-06-30 03:23 UTC
Labels: bug, awaiting response
