### ISSUE TITLE
[Suggestion] Let zoners define multiple checkpoints into one cp

### ISSUE THREAD

**Issue by ImDini** [surftimer/SurfTimer#385] opened 2022-02-03 13:33 UTC
Currently you cannot place 2 checkpoints and have both be checkpoint 1 for example, instead it does checkpoint 0 (aka cp1) and checkpoint 1 (cp2). Suggestion is just when you go into edit zones and you do "set zone type" we should be able to define the same zoneid as an already existing checkpoint for maps that require 2 sided checkpoints.

If you try editing the zoneid within db (which honestly should work) it somehow does not like that at all and can alter completely different maps when trying to do that. If that somehow doesn't alter others maps for some it won't work anyways. Timer will just not start till you change it back to normal zoneid's.

**Comment by dPexxIAM** [comment] 2022-07-25 16:48
duplicate of https://github.com/surftimer/SurfTimer/issues/199

**Closed by dPexxIAM** 2022-07-25 16:48 UTC
Labels: enhancement
