### ISSUE TITLE
[BUG]BOT Reply bug

### ISSUE THREAD

**Issue by Xedoo** [surftimer/SurfTimer#76] opened 2020-04-28 08:58 UTC
**Describe the bug**
Example : first guy in top have map record 2 min and 23 seconds and 12 ms ok? The another have a different time. When you want to see the bot reply 1 time bot will be on first guy and second time bot will be an another guy different time. In TAB appear a random guy with random time not the First guy with the best time. After sm_fixbots the problem is the same. Map record and bonus same problem. 

**Additional context**
Another thing, when i use spec on bot or sometimes on players, when i want to play again, !r or !back or !start, any command to 'revive' sometimes the screen goes on black and i need to reconnect to the server to play again. Not happen only for me.

EDIT : BOT Replay for stages is like finish the same stage 3 times and after the next stage again 3 times...

**Comment by TheGunter24** [comment] 2020-05-06 17:56
could you try to rewrite it ? cant barely understand what you want
some screenshots would be awesome

regarding your edit:
stage replays are ment to run 3 times â stage

**Comment by Kyli3Boi** [comment] 2020-05-13 16:04
I think what he is trying to say is the same issue that i have as well as BlazerV60 (on discord)

Our replay bots are not playing the server record replay but rather some other random player.
IE bot is replaying a run of a person ranked 7th,10th,20th rather than the person that is ranked 1st.

Fixbot does nothing as it just loads the same bot.

I even have a bot replaying a run of a person that starts, gets half way, fails, starts again and then completes and the bot is replaying all of this

**Comment by LubricantJam** [comment] 2020-05-13 16:43
@fluffyst I believe has a fix for this, he would have to merge it.

**Comment by Kyli3Boi** [comment] 2020-05-13 19:06
@LubricantJam I spoke with fluffyst and he says that the solution you thinking of is not for the same problem.

Any other suggestions? Anything i can try do?

**Comment by LubricantJam** [comment] 2020-05-13 19:21
> @LubricantJam I spoke with fluffyst and he says that the solution you thinking of is not for the same problem.
> 
> Any other suggestions? Anything i can try do? 
> 

No idea, will be a case of figuring out the problem I guess.

**Comment by Xedoo** [comment] 2020-05-13 23:01
> 
> 
> I think what he is trying to say is the same issue that i have as well as BlazerV60 (on discord)
> 
> Our replay bots are not playing the server record replay but rather some other random player.
> IE bot is replaying a run of a person ranked 7th,10th,20th rather than the person that is ranked 1st.
> 
> Fixbot does nothing as it just loads the same bot.
> 
> I even have a bot replaying a run of a person that starts, gets half way, fails, starts again and then completes and the bot is replaying all of this

Yea, that s what i want to say. Thx..

**Comment by Bara** [comment] 2020-09-27 12:04
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by dPexxIAM** [comment] 2022-06-30 03:17
not able to reproduce

**Closed by dPexxIAM** 2022-06-30 03:17 UTC
Labels: bug, awaiting response
