### ISSUE TITLE
[BUG] maxvelocity bug

### ISSUE THREAD

**Issue by Ciallo-Ani** [surftimer/SurfTimer#46] opened 2020-04-21 04:13 UTC
map sv_maxvelocity is 3500,but somehow it is 2500 to someone while it is not for everyone
here's how:
https://youtu.be/kRnEygx-9lI

**Comment by rosekick** [comment] 2020-04-21 04:16
btw,bug has happened since i used z4lab's fork timer

**Comment by TheGunter24** [comment] 2020-04-21 04:33
have you checked the "ck_maptier" setting ?
https://abload.de/img/anmerkung2020-04-2106yakp5.png

**Comment by rosekick** [comment] 2020-04-21 05:42
> have you checked the "ck_maptier" setting ?
> https://abload.de/img/anmerkung2020-04-2106yakp5.png

yeah
https://imgur.com/SHwSJkB
but it shouldn't limit in 2500 though map have no settings

**Comment by jaexo** [comment] 2020-04-21 08:37
I've also had this bug happen to me and it didn't fix until the server owner did a restart.

**Comment by g2dgaming** [comment] 2020-04-21 09:02
I'm also facing same issue, happens to random players, I even reported it to z4labs surftimer dev. but got no response, hope it gets fixed ASAP ;)

**Comment by qawery-just-sad** [comment] 2020-04-21 10:35
do you use `utf8mb4_unicode_ci` in your db? also a long time ago there was the same issue but the guy didn't have his main.cfg in csgo/cfg/sourcemod/surftimer

**Comment by qawery-just-sad** [comment] 2020-04-21 12:11
btw just looked at your (@rosekick ) fork from z4lab in surftimer.sp u missing `#include "surftimer/sql2.sp"` line 1590

**Comment by 13ace37** [comment] 2020-04-21 12:25
sql2 isnt a thing anymore

**Comment by qawery-just-sad** [comment] 2020-04-21 12:29
well look at his fork

**Comment by sneak-it** [comment] 2020-04-21 12:40
We will not support anything but the latest release here, confirm you are not running an alerted fork or old version.

**Comment by rosekick** [comment] 2020-04-21 15:51
> We will not support anything but the latest release here, confirm you are not running an alerted fork or old version.

my old fork isnt a thing anymore，and pretty sure i'm using the latest release

**Comment by rosekick** [comment] 2020-04-21 15:54
> We will not support anything but the latest release here, confirm you are not running an alerted fork or old version.

my old fork isnt a thing anymore，and pretty sure i'm using the latest release

**Comment by g2dgaming** [comment] 2020-04-21 17:29
yeah, even I'm using the latest release still facing this issue!

**Comment by sneak-it** [comment] 2020-04-22 05:21
Do you use any max speed zones?

Relevant: https://github.com/olokos/Surftimer-olokos/blob/5454ef5c5b4ec5798624887e0a6bad7211f95d3a/addons/sourcemod/scripting/surftimer/hooks.sp#L855

**Comment by Kyli3Boi** [comment] 2020-10-03 16:13
Not able to reproduce. 

Have tested with max speed zones and once leaving the zone the speed is uncapped.

**Comment by dPexxIAM** [comment] 2022-06-30 03:12
@Ciallo-Ani feel free to re-open if you encounter this issue, but i believe it to be fixed with https://github.com/surftimer/SurfTimer/commit/6e126874e88da687c84864e9159e4b566681760b

**Closed by dPexxIAM** 2022-06-30 03:12 UTC
Labels: bug, awaiting response, template-unused
